version: "3"
services:

  base:
    build: base/
    image: mo-vault:base
    container_name: mo.vault.base

  # spki:
  #   build: 
  #     context: spki/

  #   image: mo-vault:spki
  #   container_name: mo.vault.spki
  #   volumes:
  #     - ${PWD}/spki:/root
  #     - ${PWD}/local/spki:/spki
      
  # encryption as a service
  eaas:
    depends_on: 
      - base
    build: 
      context: softhsm2-proxy/
      #  This part was help to pass vairables from docker-compose file to DockerFile
      args:
        HSM_KEYSHARES: ${HSM_KEYSHARES}
        HSM_KEY_THESHOLD: ${HSM_KEY_THESHOLD}
        MY_TOKENLABEL: ${MY_TOKENLABEL}
        MY_PKCS11_PROXY_PORT: ${MY_PKCS11_PROXY_PORT}
    image: mo-vault:eaas
    container_name: mo.vault.eaas

    ports:
      - "${MY_PKCS11_PROXY_PORT}:${MY_PKCS11_PROXY_PORT}"
      - "8443:8443"

    volumes:
      # - ${PWD}/secrets/PIN_PRO.testing.public.asc:/tmp/public.asc
      - ${PWD}/softhsm2-proxy:/eaas
      - $PWD/local/tokens/user02:/var/tokens

  dropzone:
    depends_on: 
      - eaas
    build: 

      context: dropzone/
      args:
        DROPZONE_PORT: ${DROPZONE_PORT}
        DROPZONE_SECRET_PATH: ${DROPZONE_SECRET_PATH}
        DROPZONE_SECRET_VERSION: ${DROPZONE_SECRET_VERSION}
      
    image: mo-vault:dropzone
    container_name: mo.vault.dropzone
    ports: 
      - "${DROPZONE_PORT}:${DROPZONE_PORT}"
    links:
      - "eaas:mo.vault.eaas"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://mo.vault.eaas:8443"]
      interval: 30s
      timeout: 10s
      retries: 5
      
    volumes:
      - ${PWD}/dropzone:/dropzone
      - ${PWD}/local/dropzone/keks:/dropzone/keks
      - $PWD/local/dropzone/remote:/home/
